Repository WordPress/wporg-two-factor, pull requests merged in 2023-05, with the labels that each got.

#161 Only show the reauth modal if a primary 2FA provider is enabled
  settings/src/components/account-status.js
  settings/src/components/backup-codes.js
  settings/src/components/email-address.js
  settings/src/components/password.js
  settings/src/components/revalidate-modal.js
  settings/src/components/tests/password/password.test.js
  settings/src/components/tests/utlitites.test.js
  settings/src/components/totp.js
  settings/src/script.js
  settings/src/utilities.js
Labels: bug, ui

#177 Fix dirty password prevent email from saving
  settings/src/components/tests/utlitites.test.js
  settings/src/script.js
  settings/src/utilities.js
Labels: bug, ui, priority: medium

#187 Add try...catch to handle backup API failure
  settings/src/components/backup-codes.js
Labels: bug, ui, priority: medium

#197 Extract variables for DRYness
  settings/src/components/account-status.js
  settings/src/components/backup-codes.js
  settings/src/components/totp.js
  settings/src/script.js
  settings/src/utilities.js
Labels: enhancement
